<?php

/**
 * @file
 * Component Module.
 */

/**
 * Implements hook_theme() for Component templates.
 */
function component_theme() {
  return [
    'component_html' => [
      'variables' => [
        'html_template' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 *   Create a Drupal library entry for each component. This is what the
 *   component uses to load the css/js.
 * 
 *  eg: 'component/example/tabs'
 */
function component_library_info_build() {
  $libraries = [];

  $discovery = \Drupal::service('component.component_discovery');
  $components = $discovery->getComponents();

  foreach ($components as $component) {
    $info = $component->info;
    $path = $component->subpath;
    $libraries[$info['machine_name']]  = [
      'js' =>  _component_build_library($info['js'], $path),
      'css' => [
        'component' => _component_build_library($info['css'], $path),
      ],
      'dependencies' =>  $info['dependencies']
    ];
  }

  return $libraries;
}

/**
 * Helper function to process and build library assets.
 */
function _component_build_library($assets, $path) {
  $processed = [];
  foreach ($assets as $asset_file => $asset_data) {
    // Allow external assets to use absolute path.
    if (!empty($asset_data['type']) && $asset_data['type'] == 'external') {
      $asset_path = $asset_file;
    }
    else {
      $asset_path = '/' . $path . '/' . $asset_file;
    }

    $processed[$asset_path] = $asset_data;
  }

  return $processed;
}
