<?php

/**
 * @file
 * Contains component_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function component_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the component_field module.
    case 'help.page.component_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a field for selecting and rendering a component.') . '</p>';
      return $output;

    default:
  }
}
